sudo: false
language: go
matrix:
  include:
  - go: "1.12.x"
  - go: "1.13.x"
  - go: "1.14.x"

env:
  - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls

script:
  - go get -v -t ./...
  - go get github.com/modocache/gover
  - go test -coverprofile=gear.coverprofile
  - go test -coverprofile=logging.coverprofile ./logging
  - go test -coverprofile=cors.coverprofile ./middleware/cors
  - go test -coverprofile=favicon.coverprofile ./middleware/favicon
  # - go test -coverprofile=grpc.coverprofile ./middleware/grpc
  - go test -coverprofile=secure.coverprofile ./middleware/secure
  - go test -coverprofile=static.coverprofile ./middleware/static
  - go test -coverprofile=requestid.coverprofile ./middleware/requestid
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
